{
  "props": [],
  "components": {
    "fileChooserAlt": {
      "type": "script\\FileChooserScript",
      "x": 592,
      "y": 352,
      "props": {
        "filterName": "Все файлы",
        "filterExtensions": "*.*",
        "filterAny": "0",
        "inputNode": "edit",
        "actionNode": "button32"
      }
    },
    "fileChooser": {
      "type": "script\\FileChooserScript",
      "x": 384,
      "y": 288,
      "props": {
        "multiple": false,
        "filterName": "Androcut Automatical Uninstall Script (*.aaus)",
        "filterExtensions": "*.aaus",
        "filterAny": "0",
        "actionNode": "button34"
      }
    },
    "dirChooser": {
      "type": "script\\DirectoryChooserScript",
      "x": 528,
      "y": 176,
      "props": {
        "inputNode": "edit",
        "actionNode": "buttonfldr"
      }
    }
  }
}