{
  "props": [],
  "components": {
    "fileChooser5": {
      "type": "script\\FileChooserScript",
      "x": 384,
      "y": 496,
      "props": {
        "filterName": "Все файлы",
        "filterExtensions": "*.*",
        "filterAny": "0",
        "inputNode": "editimg",
        "actionNode": "button27"
      }
    },
    "ini": {
      "type": "script\\storage\\IniStorage",
      "x": 592,
      "y": 416,
      "props": {
        "path": "https://samarin-dev.github.io/androcut/apps.db",
        "autoSave": false,
        "multiLineValues": "1"
      }
    },
    "fileChooserAlt": {
      "type": "script\\FileChooserScript",
      "x": 384,
      "y": 400,
      "props": {
        "filterName": "Все файлы",
        "filterExtensions": "*.*",
        "filterAny": "0",
        "inputNode": "edit",
        "actionNode": "buttonfldr"
      }
    },
    "fileChooser": {
      "type": "script\\FileChooserScript",
      "x": 384,
      "y": 288,
      "props": {
        "multiple": false,
        "initialDirectory": "/scripts",
        "filterName": "Androcut Automatical Uninstall Script (*.aaus)",
        "filterExtensions": "*.aaus",
        "filterAny": true,
        "actionNode": "button34"
      }
    },
    "fileChooser3": {
      "type": "script\\FileChooserScript",
      "x": 624,
      "y": 288,
      "props": {
        "saveDialog": true,
        "initialDirectory": "/scripts",
        "filterName": "Androcut Automatical Uninstall Script (*.aaus)",
        "filterExtensions": "*.aaus",
        "filterAny": true,
        "inputNode": "scriptpath",
        "actionNode": "buttonpath"
      }
    },
    "fileChooser4": {
      "type": "script\\FileChooserScript",
      "x": 704,
      "y": 288,
      "props": {
        "initialDirectory": "/scripts",
        "filterName": "Androcut Automatical Uninstall Script (*.aaus)",
        "filterExtensions": "*.aaus",
        "filterAny": true,
        "inputNode": "scriptpath",
        "actionNode": "buttonopen"
      }
    },
    "dirChooser": {
      "type": "script\\DirectoryChooserScript",
      "x": 528,
      "y": 176,
      "props": {
        "inputNode": "edit",
        "actionNode": "buttonfldr"
      }
    }
  }
}